name       : shaderc
version    : '2023.3'
release    : 7
source     :
    - https://github.com/google/shaderc/archive/refs/tags/v2023.3.tar.gz : 7f66435c59797cdc6370dc97aa5cab21651385ac6c5159975566d51cc3e6650f
homepage   : https://github.com/google/shaderc
license    : Apache-2.0
component  : programming.tools
summary    : A collection of tools, libraries, and tests for Vulkan shader compilation
description: |
    A collection of tools, libraries and tests for shader compilation. At the moment it includes both glslc, a command line compiler for GLSL/HLSL to SPIR-V, and libshaderc, a library API for accessing glslc functionality.
builddeps  :
    - pkgconfig(SPIRV-Tools)
    - asciidoctor
    - glslang-devel
setup      : |
    %apply_patches
    echo \"shaderc v%version%\" > glslc/src/build-version.inc
    echo \" - spirv-tools $(spirv-link --version | perl -ne 'print $1 if /(v\d+\.\d)/;')\" >> glslc/src/build-version.inc
    echo \" - glslang v$(glslangValidator --version | head -n1 | perl -ne 'print $1 if /:(\d.*\d)/;')\" >> glslc/src/build-version.inc
    sed -i "s|@VERSION@|%version%|" libshaderc/CMakeLists.txt
    rm -rf third_party

    %cmake_ninja -DSHADERC_SKIP_TESTS=ON -DCMAKE_SKIP_RPATH=ON -DPYTHON_EXE=python3
build      : |
    %ninja_build
    asciidoctor -b manpage glslc/README.asciidoc -o glslc.1
install    : |
    %ninja_install
    install -Dm00644 glslc.1 $installdir/usr/share/man/man1/glslc.1
